apiVersion: v1
kind: Service
metadata:
  name: server-node-port
spec:
  type: NodePort  
  ports:
    - port: 3003
      targetPort: 3003
  selector:
    component: server



  ports:
    - name: http
      port: 3000
      nodePort: 30000
      targetPort: 3000
      protocol: TCP


 
