apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
   app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
     containers:
     - name: client-cluster-ip-service
       image: tcgdockerregistry.azurecr.io/moral-react-client
       imagePullPolicy: IfNotPresent
       ports:
       - containerPort: 80
       env:
       - name: REACT_APP_API
         value: '192.168.0.25:30006'
     imagePullSecrets:  
       - name: tcg

