apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
       app: server
    spec:
      containers:
      - name: server-service
        image: 447795736826.dkr.ecr.eu-west-2.amazonaws.com/students:node-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3003
        env:
        - name: HOST_NAME
          value: postgres-service
        - name: USER_NAME
          value: postgres
        - name: PGPORT
          value: '5432'
        - name: DATABASE_NAME
          value: storage_unit
        - name:  DATABASE_PASSWORD
          value: tcg1
        - name:  JWT_SECRET
          value: dbnnf45d
      imagePullSecrets:  
        - name: tcg

